/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/

var x = 0;
var y = 1;
var fib = 0;
var total = 0;

do{
    fib = x + y;
    console.log(fib);
    x = y;
    y = fib;
    
    if (fib % 2 === 0){
        total += fib;
    }
    
}while(fib < 4000000);
console.log('gran total:', total);
